# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(570, 636)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainMenu.sizePolicy().hasHeightForWidth())
        MainMenu.setSizePolicy(sizePolicy)
        MainMenu.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(MainMenu)
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(18)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_created = QtWidgets.QLabel(MainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_created.sizePolicy().hasHeightForWidth())
        self.lbl_created.setSizePolicy(sizePolicy)
        self.lbl_created.setMinimumSize(QtCore.QSize(361, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_created.setFont(font)
        self.lbl_created.setObjectName("lbl_created")
        self.gridLayout.addWidget(self.lbl_created, 6, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_2.setVerticalSpacing(23)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_config = QtWidgets.QPushButton(MainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_config.sizePolicy().hasHeightForWidth())
        self.btn_config.setSizePolicy(sizePolicy)
        self.btn_config.setMinimumSize(QtCore.QSize(360, 50))
        self.btn_config.setMaximumSize(QtCore.QSize(390, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_config.setFont(font)
        self.btn_config.setObjectName("btn_config")
        self.gridLayout_2.addWidget(self.btn_config, 0, 0, 1, 1)
        self.btn_multi = QtWidgets.QPushButton(MainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_multi.sizePolicy().hasHeightForWidth())
        self.btn_multi.setSizePolicy(sizePolicy)
        self.btn_multi.setMinimumSize(QtCore.QSize(360, 50))
        self.btn_multi.setMaximumSize(QtCore.QSize(390, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_multi.setFont(font)
        self.btn_multi.setObjectName("btn_multi")
        self.gridLayout_2.addWidget(self.btn_multi, 2, 0, 1, 1)
        self.btn_single = QtWidgets.QPushButton(MainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_single.sizePolicy().hasHeightForWidth())
        self.btn_single.setSizePolicy(sizePolicy)
        self.btn_single.setMinimumSize(QtCore.QSize(360, 50))
        self.btn_single.setMaximumSize(QtCore.QSize(390, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_single.setFont(font)
        self.btn_single.setObjectName("btn_single")
        self.gridLayout_2.addWidget(self.btn_single, 1, 0, 1, 1)
        self.btn_help = QtWidgets.QPushButton(MainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_help.sizePolicy().hasHeightForWidth())
        self.btn_help.setSizePolicy(sizePolicy)
        self.btn_help.setMinimumSize(QtCore.QSize(360, 50))
        self.btn_help.setMaximumSize(QtCore.QSize(390, 50))
        self.btn_help.setIconSize(QtCore.QSize(30, 30))
        self.btn_help.setObjectName("btn_help")
        self.gridLayout_2.addWidget(self.btn_help, 3, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(MainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(500, 230))
        self.label.setMaximumSize(QtCore.QSize(16777215, 230))
        self.label.setStyleSheet("image: url(:/images/logo.png);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 1)

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "Main Menu"))
        self.lbl_created.setText(_translate("MainMenu", "<html><head/><body><p align=\"center\">Created By Or Cohen &amp; Eliran Menashe<br/>Supervisor: Dr. Renata Avros<br/>Date: 01/05/2020</p></body></html>"))
        self.btn_config.setText(_translate("MainMenu", "Configuration"))
        self.btn_multi.setText(_translate("MainMenu", "Analyze Multiple Tweets"))
        self.btn_single.setText(_translate("MainMenu", "Analyze Single Tweet"))
        self.btn_help.setText(_translate("MainMenu", "Help"))

import source_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainMenu = QtWidgets.QWidget()
    ui = Ui_MainMenu()
    ui.setupUi(MainMenu)
    MainMenu.show()
    sys.exit(app.exec_())

