# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MultipleAnalyzer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MultipleAnalayzer(object):
    def setupUi(self, MultipleAnalayzer):
        MultipleAnalayzer.setObjectName("MultipleAnalayzer")
        MultipleAnalayzer.resize(564, 581)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MultipleAnalayzer.setWindowIcon(icon)
        MultipleAnalayzer.setStyleSheet("#lbl_title {\n"
"font: 75 20pt \"Microsoft YaHei UI\";\n"
"font-weight: bold;\n"
"qproperty-alignment: AlignCenter;\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #3643f7, stop:1 #3643f7);\n"
"}\n"
"\n"
"#btn_homepage {\n"
"background: transparent;\n"
"border-radius: 19px;\n"
"}\n"
"\n"
"#btn_homepage::hover {\n"
"background: #3f72af;\n"
"}\n"
"\n"
"#btn_help {\n"
"background: transparent;\n"
"border-radius: 19px;\n"
"}\n"
"\n"
"#btn_help::hover {\n"
"background: #3f72af;\n"
"}\n"
"\n"
"#btn_start, #btn_classify, #btn_save {\n"
"font: 75 13pt \"Microsoft YaHei UI\";\n"
"font-weight: bold;\n"
"}\n"
"\n"
"QProgressBar:horizontal {\n"
"border: 1px solid gray;\n"
"border-radius: 3px;\n"
"background: white;\n"
"padding: 0px;\n"
"}\n"
"QProgressBar::chunk:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #a8ff78, stop: 1 #78ffd6);\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(MultipleAnalayzer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.btn_homepage = QtWidgets.QToolButton(MultipleAnalayzer)
        self.btn_homepage.setAutoFillBackground(False)
        self.btn_homepage.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/homepage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_homepage.setIcon(icon1)
        self.btn_homepage.setIconSize(QtCore.QSize(35, 35))
        self.btn_homepage.setObjectName("btn_homepage")
        self.horizontalLayout_11.addWidget(self.btn_homepage)
        self.btn_help = QtWidgets.QToolButton(MultipleAnalayzer)
        self.btn_help.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_help.setIcon(icon2)
        self.btn_help.setIconSize(QtCore.QSize(35, 35))
        self.btn_help.setObjectName("btn_help")
        self.horizontalLayout_11.addWidget(self.btn_help)
        self.lbl_title = QtWidgets.QLabel(MultipleAnalayzer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_title.sizePolicy().hasHeightForWidth())
        self.lbl_title.setSizePolicy(sizePolicy)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.horizontalLayout_11.addWidget(self.lbl_title)
        spacerItem = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(18, 26, 60, 18)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(MultipleAnalayzer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.combobox_model = QtWidgets.QComboBox(MultipleAnalayzer)
        self.combobox_model.setObjectName("combobox_model")
        self.horizontalLayout_6.addWidget(self.combobox_model)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.groupbox_inputs = QtWidgets.QGroupBox(MultipleAnalayzer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupbox_inputs.sizePolicy().hasHeightForWidth())
        self.groupbox_inputs.setSizePolicy(sizePolicy)
        self.groupbox_inputs.setObjectName("groupbox_inputs")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupbox_inputs)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setContentsMargins(14, 7, 14, 11)
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupbox_inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupbox_inputs)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textbox_tweets_file = QtWidgets.QLineEdit(self.groupbox_inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textbox_tweets_file.sizePolicy().hasHeightForWidth())
        self.textbox_tweets_file.setSizePolicy(sizePolicy)
        self.textbox_tweets_file.setMinimumSize(QtCore.QSize(200, 0))
        self.textbox_tweets_file.setMaximumSize(QtCore.QSize(500, 16777215))
        self.textbox_tweets_file.setObjectName("textbox_tweets_file")
        self.verticalLayout_3.addWidget(self.textbox_tweets_file)
        self.checkbox_header = QtWidgets.QCheckBox(self.groupbox_inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_header.sizePolicy().hasHeightForWidth())
        self.checkbox_header.setSizePolicy(sizePolicy)
        self.checkbox_header.setChecked(True)
        self.checkbox_header.setObjectName("checkbox_header")
        self.verticalLayout_3.addWidget(self.checkbox_header)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_tweets_file = QtWidgets.QPushButton(self.groupbox_inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_tweets_file.sizePolicy().hasHeightForWidth())
        self.btn_tweets_file.setSizePolicy(sizePolicy)
        self.btn_tweets_file.setMinimumSize(QtCore.QSize(35, 0))
        self.btn_tweets_file.setMaximumSize(QtCore.QSize(35, 16777215))
        self.btn_tweets_file.setObjectName("btn_tweets_file")
        self.verticalLayout_5.addWidget(self.btn_tweets_file)
        spacerItem1 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addWidget(self.groupbox_inputs)
        self.groupbox_trainparams = QtWidgets.QGroupBox(MultipleAnalayzer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupbox_trainparams.sizePolicy().hasHeightForWidth())
        self.groupbox_trainparams.setSizePolicy(sizePolicy)
        self.groupbox_trainparams.setMaximumSize(QtCore.QSize(16777215, 102))
        self.groupbox_trainparams.setObjectName("groupbox_trainparams")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupbox_trainparams)
        self.horizontalLayout_3.setContentsMargins(14, 7, 14, 11)
        self.horizontalLayout_3.setSpacing(7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.groupbox_trainparams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.groupbox_trainparams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.spinbox_rand_tweets = QtWidgets.QSpinBox(self.groupbox_trainparams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinbox_rand_tweets.sizePolicy().hasHeightForWidth())
        self.spinbox_rand_tweets.setSizePolicy(sizePolicy)
        self.spinbox_rand_tweets.setMinimumSize(QtCore.QSize(0, 20))
        self.spinbox_rand_tweets.setMaximumSize(QtCore.QSize(60, 20))
        self.spinbox_rand_tweets.setMinimum(3)
        self.spinbox_rand_tweets.setMaximum(9000)
        self.spinbox_rand_tweets.setProperty("value", 50)
        self.spinbox_rand_tweets.setObjectName("spinbox_rand_tweets")
        self.verticalLayout_8.addWidget(self.spinbox_rand_tweets)
        self.spinbox_threshold = QtWidgets.QDoubleSpinBox(self.groupbox_trainparams)
        self.spinbox_threshold.setMinimumSize(QtCore.QSize(0, 20))
        self.spinbox_threshold.setMaximumSize(QtCore.QSize(60, 20))
        self.spinbox_threshold.setSpecialValueText("")
        self.spinbox_threshold.setDecimals(1)
        self.spinbox_threshold.setMinimum(0.1)
        self.spinbox_threshold.setMaximum(1.0)
        self.spinbox_threshold.setSingleStep(0.1)
        self.spinbox_threshold.setProperty("value", 0.5)
        self.spinbox_threshold.setObjectName("spinbox_threshold")
        self.verticalLayout_8.addWidget(self.spinbox_threshold)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.groupbox_trainparams)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(14, 10, 14, 10)
        self.horizontalLayout_4.setSpacing(31)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_start = QtWidgets.QPushButton(MultipleAnalayzer)
        self.btn_start.setMinimumSize(QtCore.QSize(0, 35))
        self.btn_start.setMaximumSize(QtCore.QSize(16777215, 35))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/run.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_start.setIcon(icon3)
        self.btn_start.setIconSize(QtCore.QSize(30, 30))
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout_4.addWidget(self.btn_start)
        self.btn_classify = QtWidgets.QPushButton(MultipleAnalayzer)
        self.btn_classify.setEnabled(False)
        self.btn_classify.setMinimumSize(QtCore.QSize(0, 35))
        self.btn_classify.setMaximumSize(QtCore.QSize(16777215, 35))
        self.btn_classify.setIconSize(QtCore.QSize(25, 25))
        self.btn_classify.setObjectName("btn_classify")
        self.horizontalLayout_4.addWidget(self.btn_classify)
        self.btn_save = QtWidgets.QPushButton(MultipleAnalayzer)
        self.btn_save.setEnabled(False)
        self.btn_save.setMinimumSize(QtCore.QSize(0, 35))
        self.btn_save.setMaximumSize(QtCore.QSize(16777215, 35))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/export-excel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save.setIcon(icon4)
        self.btn_save.setIconSize(QtCore.QSize(35, 35))
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_4.addWidget(self.btn_save)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(14, 8, 14, 0)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_13 = QtWidgets.QLabel(MultipleAnalayzer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_10.addWidget(self.label_13)
        self.label_12 = QtWidgets.QLabel(MultipleAnalayzer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_10.addWidget(self.label_12)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.progressbar_tweets = QtWidgets.QProgressBar(MultipleAnalayzer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressbar_tweets.sizePolicy().hasHeightForWidth())
        self.progressbar_tweets.setSizePolicy(sizePolicy)
        self.progressbar_tweets.setMinimumSize(QtCore.QSize(0, 17))
        self.progressbar_tweets.setMaximumSize(QtCore.QSize(16777215, 17))
        self.progressbar_tweets.setMinimum(0)
        self.progressbar_tweets.setMaximum(100)
        self.progressbar_tweets.setProperty("value", 0)
        self.progressbar_tweets.setAlignment(QtCore.Qt.AlignCenter)
        self.progressbar_tweets.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressbar_tweets.setObjectName("progressbar_tweets")
        self.verticalLayout_11.addWidget(self.progressbar_tweets)
        self.progressbar_batch = QtWidgets.QProgressBar(MultipleAnalayzer)
        self.progressbar_batch.setMinimumSize(QtCore.QSize(0, 17))
        self.progressbar_batch.setMaximumSize(QtCore.QSize(16777215, 17))
        self.progressbar_batch.setProperty("value", 0)
        self.progressbar_batch.setAlignment(QtCore.Qt.AlignCenter)
        self.progressbar_batch.setObjectName("progressbar_batch")
        self.verticalLayout_11.addWidget(self.progressbar_batch)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)

        self.retranslateUi(MultipleAnalayzer)
        QtCore.QMetaObject.connectSlotsByName(MultipleAnalayzer)

    def retranslateUi(self, MultipleAnalayzer):
        _translate = QtCore.QCoreApplication.translate
        MultipleAnalayzer.setWindowTitle(_translate("MultipleAnalayzer", "Multiple Tweets Analyzer"))
        self.btn_homepage.setToolTip(_translate("MultipleAnalayzer", "Back To HomePage"))
        self.btn_help.setToolTip(_translate("MultipleAnalayzer", "Open Help Documentation"))
        self.lbl_title.setText(_translate("MultipleAnalayzer", "Multiple Tweets Analyzer"))
        self.label.setText(_translate("MultipleAnalayzer", "Select Model:"))
        self.groupbox_inputs.setTitle(_translate("MultipleAnalayzer", "Input File"))
        self.label_2.setText(_translate("MultipleAnalayzer", "Tweets File:"))
        self.label_3.setText(_translate("MultipleAnalayzer", "Have Header?"))
        self.checkbox_header.setText(_translate("MultipleAnalayzer", "Included"))
        self.btn_tweets_file.setText(_translate("MultipleAnalayzer", "..."))
        self.groupbox_trainparams.setTitle(_translate("MultipleAnalayzer", "Predict Parameters"))
        self.label_7.setText(_translate("MultipleAnalayzer", "Random Tweets:"))
        self.label_8.setText(_translate("MultipleAnalayzer", "Threshold:"))
        self.btn_start.setText(_translate("MultipleAnalayzer", "Predict"))
        self.btn_classify.setText(_translate("MultipleAnalayzer", "Change Classify"))
        self.btn_save.setText(_translate("MultipleAnalayzer", "Export"))
        self.label_13.setText(_translate("MultipleAnalayzer", "Tweets"))
        self.label_12.setText(_translate("MultipleAnalayzer", "Batch"))

import source_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MultipleAnalayzer = QtWidgets.QWidget()
    ui = Ui_MultipleAnalayzer()
    ui.setupUi(MultipleAnalayzer)
    MultipleAnalayzer.show()
    sys.exit(app.exec_())

